FROM python:3.11-slim-bookworm

# 设置工作目录
WORKDIR /app

# 将当前目录的内容复制到容器中的/app目录下
COPY . /app

# 安装所需的Python包
RUN pip install --no-cache-dir open-webui==0.3.13

# 暴露端口
EXPOSE 8080

# 设置容器启动时执行的命令
CMD ["open-webui", "serve"]
